.gitignore
build.gradle
src/main/java/CaffeineCoder/recipic/RecipicApplication.java
src/main/java/CaffeineCoder/recipic/brand/DTO/IngredientDTO.java
src/main/java/CaffeineCoder/recipic/brand/controller/BrandController.java
src/main/java/CaffeineCoder/recipic/brand/model/Brand.java
src/main/java/CaffeineCoder/recipic/brand/model/BrandIngredient.java
src/main/java/CaffeineCoder/recipic/brand/model/BrandIngredientId.java
src/main/java/CaffeineCoder/recipic/brand/model/Ingredient.java
src/main/java/CaffeineCoder/recipic/brand/repository/BrandIngredientRepository.java
src/main/java/CaffeineCoder/recipic/brand/repository/BrandRepository.java
src/main/java/CaffeineCoder/recipic/brand/repository/IngredientRepository.java
src/main/java/CaffeineCoder/recipic/brand/service/BrandService.java
src/main/resources/application.properties

#4 브랜드별 재료 반환 

---

src/main/java/CaffeineCoder/recipic/global/error/ErrorCode.java
src/main/java/CaffeineCoder/recipic/global/error/ErrorResponse.java
src/main/java/CaffeineCoder/recipic/global/error/GlobalExceptionHandler.java
src/main/java/CaffeineCoder/recipic/global/error/exception/InvalidValueException.java
src/main/java/CaffeineCoder/recipic/global/response/ApiResponse.java
src/main/java/CaffeineCoder/recipic/global/util/ApiUtils.java

PR 타입
반영 브랜치
feat/global ➡️ main
- 전역 에러 처리 코드 구현
- 전역 API 응답 유틸 함수 구현
신규 API 목록
x
close #20

Feat/global: 전역 에러 처리 & 전역 API 응답 유틸 함수 추가

---

src/main/java/CaffeineCoder/recipic/domain/authentication/api/AuthController.java
src/main/java/CaffeineCoder/recipic/domain/authentication/api/OAuthLoginService.java
src/main/java/CaffeineCoder/recipic/domain/authentication/domain/AuthTokensGenerator.java
src/main/java/CaffeineCoder/recipic/domain/jwtSecurity/jwt/TokenProvider.java
src/main/java/CaffeineCoder/recipic/global/error/ErrorCode.java
src/main/java/CaffeineCoder/recipic/global/error/ErrorResponse.java
src/main/java/CaffeineCoder/recipic/global/error/GlobalExceptionHandler.java
src/main/java/CaffeineCoder/recipic/global/error/exception/InvalidValueException.java
src/main/java/CaffeineCoder/recipic/global/response/ApiResponse.java
src/main/java/CaffeineCoder/recipic/global/util/ApiUtils.java

feat/superuser ➡️ main
- 슈퍼유저 생성 API 구현
1. `/api/auth/admin`: 기한 7일짜리 accesstoken 발급
close #27

Feat/superuser: 슈퍼 유저 생성

---

build.gradle
src/main/java/CaffeineCoder/recipic/domain/brand/api/BrandController.java
src/main/java/CaffeineCoder/recipic/domain/brand/api/BrandService.java
src/main/java/CaffeineCoder/recipic/domain/brand/domain/Brand.java
src/main/java/CaffeineCoder/recipic/domain/brand/domain/BrandIngredient.java
src/main/java/CaffeineCoder/recipic/domain/brand/domain/Ingredient.java
src/main/java/CaffeineCoder/recipic/domain/jwtSecurity/config/SecurityConfig.java
src/main/java/CaffeineCoder/recipic/domain/swagger/OpenApiConfig.java

이슈번호 #24 
기능
브랜드의 각 재료에 대한 내용을 데이터베이스에 저장
api
api/brand/add-ingredient
테스트
재료 추가 후 /api/brand/ingredients 테스트

Feat/#24 : 브랜드 별 재료 추가하는 API

---

src/main/java/CaffeineCoder/recipic/domain/recipe/api/RecipeController.java
src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeService.java
src/main/java/CaffeineCoder/recipic/domain/recipe/domain/Recipe.java
src/main/java/CaffeineCoder/recipic/domain/recipe/dto/RecipeDto.java

feat/recipe/detail ➡️ main
- 레시피 상세 페이지 API 구현
/api/recipe/detail/{recipeId}
#7

✨feat: 레시피 상세 페이지 API 구현

---

src/main/java/CaffeineCoder/recipic/domain/comment/api/CommentController.java
src/main/java/CaffeineCoder/recipic/domain/comment/api/CommentService.java
src/main/java/CaffeineCoder/recipic/domain/comment/dao/CommentRepository.java
src/main/java/CaffeineCoder/recipic/domain/comment/domain/Comment.java
src/main/java/CaffeineCoder/recipic/domain/comment/dto/CommentRequestDto.java

이슈 번호 : #35 
기능
등록된 게시글에 댓글 작성 : /api/recipe/comment
테스트

feat: 댓글 작성 (#35)

---

src/main/java/CaffeineCoder/recipic/domain/authentication/api/AuthController.java
src/main/java/CaffeineCoder/recipic/domain/jwtSecurity/controller/JwtController.java
src/main/java/CaffeineCoder/recipic/domain/jwtSecurity/controller/dto/AccessTokenDto.java
src/main/java/CaffeineCoder/recipic/domain/jwtSecurity/controller/dto/TokenResponseDto.java
src/main/java/CaffeineCoder/recipic/global/util/JwtUtils.java

feat/jwt ➡️ main
- JWT reissue 로직 변경,JWT 로직 리팩토링
x
x

Feat/jwt: JWT reissue 로직 변경,JWT 로직 리팩토링

---

src/main/java/CaffeineCoder/recipic/domain/recipe/api/RecipeController.java
src/main/java/CaffeineCoder/recipic/domain/recipe/api/RecipeRankAPI.java
src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeRankService.java
src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeService.java
src/main/java/CaffeineCoder/recipic/domain/recipe/dao/RecipeIngredientRepository.java
src/main/java/CaffeineCoder/recipic/domain/recipe/dto/RecipeDto.java
src/main/java/CaffeineCoder/recipic/domain/scrap/dao/ScrapRepository.java

feat/scrap ➡️ main
- 레시피 랭킹 API 추가
`/api/recipe/rank/normal`: 일반인 레시피 랭킹 조회 (상위 5개)
`/api/recipe/rank/celebrity`: 유명인 레시피 랭킹 조회 (상위 5개)
#7

Feat/scrap: 레시피 랭킹 API 추가 

---

src/main/java/CaffeineCoder/recipic/domain/recipe/dto/IncludeIngredientDto.java
src/main/java/CaffeineCoder/recipic/domain/recipe/dto/RecipeDetailResponseDto.java
src/main/java/CaffeineCoder/recipic/domain/recipe/dto/RecipeRequestDto.java

feat/ ➡️ main
- 커밋 안된 파일 추가 커밋

✨feat: Recipe Dto 추가 커밋

---

src/main/java/CaffeineCoder/recipic/domain/comment/dao/CommentRepository.java
src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeRankService.java
src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeService.java
src/main/java/CaffeineCoder/recipic/domain/recipe/dto/RecipeResponseDto.java

feat/recipe/comment ➡️ main
- 코멘트 수가 들어간 반환용 Dto구현
x

✨feat: 코멘트 수가 들어간 반환용 Dto구현

---

src/main/java/CaffeineCoder/recipic/domain/comment/dao/CommentRepository.java
src/main/java/CaffeineCoder/recipic/domain/comment/domain/Comment.java
src/main/java/CaffeineCoder/recipic/domain/recipe/api/RecipeController.java
src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeService.java
src/main/java/CaffeineCoder/recipic/domain/recipe/domain/Recipe.java
src/main/java/CaffeineCoder/recipic/domain/recipe/dto/RecipeRequestDto.java
src/main/java/CaffeineCoder/recipic/domain/scrap/dao/ScrapRepository.java
src/main/java/CaffeineCoder/recipic/domain/scrap/domain/Scrap.java

레시피 삭제, 수정 기능 구현
feat/recipeedit ➡️ main
-  본인이 작성한 레시피 수정 기능 추가
-  본인이 작성한 레시피 삭제 기능 추가
(deleted) /api/recipe/remove : 게시물 삭제 기능
(put) /api/recipe/update : 게시물 수정 기능
본인의 게시물이 아닌 게시물 삭제를 시도하면
java.lang.IllegalArgumentException: You are not authorized to delete this recipe
이 반환됨
본인의 게시물이 아닌 게시물 수정을 시도하면
java.lang.IllegalArgumentException: You are not authorized to update this recipe
이 반환됨
#6

feat: 레시피 수정/삭제 기능 구현

---

src/main/java/CaffeineCoder/recipic/domain/recipe/api/RecipeController.java
src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeService.java
src/main/java/CaffeineCoder/recipic/domain/recipe/dao/RecipeRepository.java
src/main/java/CaffeineCoder/recipic/domain/user/api/UserRecipeApi.java
src/main/java/CaffeineCoder/recipic/domain/user/api/UserScrapApi.java

feat/ ➡️ main
- 내가 작성한 레시피 리스트 반환 
`/api/user/recipes/`
#7

Feat/user/scrap: 내가 작성한 레시피 리스트 반환 API 구현

---

src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeService.java
src/main/java/CaffeineCoder/recipic/domain/recipe/dao/RecipeRepository.java
src/main/java/CaffeineCoder/recipic/domain/scrap/dao/ScrapRepository.java
src/main/java/CaffeineCoder/recipic/domain/user/api/UserScrapApi.java
src/main/java/CaffeineCoder/recipic/domain/user/application/UserScrapService.java

feat/ ➡️ main
- 내가 스크랩한 레시피 목록 API 구현
`/api/user/scraps`
#7

✨feat: 내가 스크랩한 레시피 목록 API 구현

---

src/main/java/CaffeineCoder/recipic/global/config/WebConfig.java

feat : cors config 업데이트

---

src/main/java/CaffeineCoder/recipic/domain/jwtSecurity/config/SecurityConfig.java
src/main/java/CaffeineCoder/recipic/global/config/WebConfig.java

🐛Bug: Cors 에러 해결

---

src/main/java/CaffeineCoder/recipic/domain/brand/api/BrandController.java

api/brand/ingredients 를 post에서 get으로 변환
feat/#24 ➡️ main
- 
x
#61

feat: 재료 api 변환

---

src/main/java/CaffeineCoder/recipic/domain/comment/api/CommentController.java
src/main/java/CaffeineCoder/recipic/domain/comment/api/CommentService.java
src/main/java/CaffeineCoder/recipic/domain/comment/dao/CommentLikeRepository.java
src/main/java/CaffeineCoder/recipic/domain/comment/dao/CommentRepository.java
src/main/java/CaffeineCoder/recipic/domain/comment/dto/CommentResponseDto.java
src/main/java/CaffeineCoder/recipic/domain/user/api/UserCommentApi.java

feat/mycomment ➡️ main
- 내가 작성한 댓글 목록 확인하기
댓글을 작성한 게시물의 제목과 작성한 댓글의 좋아요 수 반환
(get) /api/recipe/comment/mycomments  : 내가 작성한 댓글 목록 반환
#35

Feat : 내가 작성한 댓글 목록 확인하기 

---

src/main/java/CaffeineCoder/recipic/domain/jwtSecurity/controller/JwtController.java

feat/ ➡️ main
토큰 재발행 로직 변경
- /auth/reissue ➡️ /api/jwt/reissue
close #66

🛠️fix: API 명세 변경

---

src/main/java/CaffeineCoder/recipic/domain/comment/api/CommentService.java
src/main/java/CaffeineCoder/recipic/domain/comment/dto/CommentResponseDto.java

레시피 아이디 추가 반환 구현
feat/ ➡️ main
- 기존 반환 내용에 레시피 아이디도 함께 반환되도록 함
x

feat: 내가 작성한 댓글 관련 dto 수정

---

src/main/java/CaffeineCoder/recipic/domain/recipe/api/RecipeController.java
src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeService.java
src/main/java/CaffeineCoder/recipic/domain/user/api/UserRecipeApi.java
src/main/java/CaffeineCoder/recipic/domain/user/api/UserScrapApi.java

feat/ ➡️ main
- 쿼리 값이 들어오지 않은 경우 처리 로직 변경

🛠️fix: 검색 비교 로직 변경

---

src/main/java/CaffeineCoder/recipic/domain/authentication/api/OAuthLoginService.java
src/main/java/CaffeineCoder/recipic/domain/brand/api/BrandService.java
src/main/java/CaffeineCoder/recipic/domain/brand/repository/BrandRepository.java
src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeService.java
src/main/java/CaffeineCoder/recipic/domain/recipe/dto/IncludeIngredientDto.java
src/main/java/CaffeineCoder/recipic/domain/recipe/dto/RecipeDetailResponseDto.java
src/main/java/CaffeineCoder/recipic/domain/user/domain/User.java

feat/recipe/response ➡️ main
- 레시피 상세 페이지 response값 수정 
response 다음과 같이 변경
```
{
"isSuccess": true,
"response": {
"recipeId": 3,
"userNickName": "하이요",
"userProfileImageUrl": "https://example.com/profile-image.jpg",
"brandName": "스타벅스",
"title": "허쉬 말아말아",
"description": "맛있는 음료수~",
"thunbnailUrl": "https://i.imgur.com/p6Cxjt3b.jpg",
"isCelebrity": "false",
"createdAt": "2024-08-24 10:41:47.0",
"status": "1",
"scrapCount": 0,
"includeIngredients": [
{
"ingredient": {
"ingredientId": 1,
"ingredientName": "자바칩",
"quantity": 1,
"unit": "개",
"cost": 600,
"calorie": 45.6
},
"count": 2
},
{
"ingredient": {
"ingredientId": 2,
"ingredientName": "초코 드리즐",
"quantity": 10,
"unit": "g",
"cost": 600,
"calorie": 45.6
},
"count": 1
}
]
}
}
```

Feat: 레시피 상세 페이지 response값 수정 

---

src/main/java/CaffeineCoder/recipic/domain/brand/api/BrandController.java
src/main/java/CaffeineCoder/recipic/domain/brand/api/BrandService.java
src/main/java/CaffeineCoder/recipic/domain/brand/domain/Brand.java
src/main/java/CaffeineCoder/recipic/domain/brand/dto/BrandDto.java
src/main/java/CaffeineCoder/recipic/domain/jwtSecurity/util/SecurityUtil.java
src/main/java/CaffeineCoder/recipic/domain/recipe/api/RecipeController.java
src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeService.java
src/main/java/CaffeineCoder/recipic/domain/recipe/dto/RecipeRequestDto.java

feat/ ➡️ main
- 유저 아이디 부분 수정
- brandId와 brandname 매핑
api/brand/list : 전체 브랜드 리스트 확인 가능 
brand list
#72

Feat: 레시피 등록 수정(브랜드ID, 유저)

---

src/main/java/CaffeineCoder/recipic/domain/brand/api/BrandService.java
src/main/java/CaffeineCoder/recipic/domain/comment/api/CommentController.java
src/main/java/CaffeineCoder/recipic/domain/comment/api/CommentService.java
src/main/java/CaffeineCoder/recipic/domain/comment/dao/CommentRepository.java
src/main/java/CaffeineCoder/recipic/domain/comment/dto/CommentDto.java
src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeService.java
src/main/java/CaffeineCoder/recipic/domain/user/domain/User.java

feat/commentList ➡️ main
- 레시피 별 댓글 리스트 불러오는 API 추가 
`GET` `/api/recipe/comment/list`
#75

Feat: 레시피 별 댓글 리스트 불러오는 API 추가 

---

src/main/java/CaffeineCoder/recipic/domain/comment/api/CommentController.java
src/main/java/CaffeineCoder/recipic/domain/comment/api/CommentService.java
src/main/java/CaffeineCoder/recipic/domain/comment/dao/CommentRepository.java

좋아요/최신 순으로 정렬
feat/ ➡️ main
- 댓글 정렬을 최신순/ 좋아요 순으로 정렬되게 수정
get /api/recipe/comment/list?recipeId={recipeId}&page=0&size=10&sortType=latest
get /api/recipe/comment/list?recipeId={recipeId)&page=0&size=10&sortType=likes
#35

feat: 댓글 정렬 수정

---

src/main/java/CaffeineCoder/recipic/domain/brand/repository/BrandRepository.java
src/main/java/CaffeineCoder/recipic/domain/brand/repository/IngredientRepository.java
src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeService.java
src/main/java/CaffeineCoder/recipic/domain/recipe/dao/RecipeIngredientRepository.java
src/main/java/CaffeineCoder/recipic/domain/recipe/dto/RecipeRequestDto.java

feat/ ➡️ main
-  재료 id 대신 재료 name으로 받아오기
-  브랜드 id 대신 브랜드 name으로 받아오기
x
#72

feat: 레시피 등록/업데이트 수정

---

src/main/java/CaffeineCoder/recipic/domain/authentication/api/OAuthLoginService.java
src/main/java/CaffeineCoder/recipic/domain/authentication/domain/oauth/OAuthInfoResponse.java
src/main/java/CaffeineCoder/recipic/domain/authentication/infra/kakao/KakaoApiClient.java
src/main/java/CaffeineCoder/recipic/domain/authentication/infra/kakao/KakaoInfoResponse.java
src/main/java/CaffeineCoder/recipic/domain/authentication/infra/naver/NaverInfoResponse.java
src/main/java/CaffeineCoder/recipic/domain/jwtSecurity/config/SecurityConfig.java
src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeService.java
src/main/java/CaffeineCoder/recipic/domain/user/domain/User.java

feat/user/profile ➡️ main
- 유저 가입 시 profile image 정보 받기

✨feat: 유저 가입 시 profile image 정보 받기

---

src/main/java/CaffeineCoder/recipic/domain/comment/api/CommentService.java
src/main/java/CaffeineCoder/recipic/domain/comment/dto/CommentDto.java
src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeService.java
src/main/java/CaffeineCoder/recipic/domain/recipe/dto/RecipeDetailResponseDto.java
src/main/java/CaffeineCoder/recipic/domain/scrap/api/ScrapService.java

feat/ ➡️ main
- RecipeDetailResponseDto 수정
- isScrapped 속성 추가
- CommentDto 수정
- isLiked 속성 추가

🛠️Fix:  RecipeDetailResponseDto, CommentDto 반환 값 수정

---

src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeRankService.java
src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeService.java
src/main/java/CaffeineCoder/recipic/domain/recipe/dto/RecipeDto.java
src/main/java/CaffeineCoder/recipic/domain/recipe/dto/RecipeResponseDto.java
src/main/java/CaffeineCoder/recipic/domain/user/application/UserService.java

feat/ ➡️ main
userId ➡️ userNickname 변경
userProfileImageUrl 추가
brand ➡️ brandName 변경
close #73

feat: RecipeResponseDto 수정 

---

src/main/java/CaffeineCoder/recipic/domain/authentication/api/OAuthLoginService.java
src/main/java/CaffeineCoder/recipic/domain/authentication/domain/AuthTokensGenerator.java
src/main/java/CaffeineCoder/recipic/domain/authentication/domain/oauth/OAuthProvider.java
src/main/java/CaffeineCoder/recipic/domain/authentication/infra/kakao/admin/AdminInfoResponse.java
src/main/java/CaffeineCoder/recipic/domain/jwtSecurity/jwt/TokenProvider.java

feat/ ➡️ main
- 관리자 토큰 생성용 API 구현 ( accessToken 만료 기한 20일)

✨feat:관리자 토큰 생성용 API 구현

---

src/main/java/CaffeineCoder/recipic/domain/user/api/UserApi.java
src/main/java/CaffeineCoder/recipic/domain/user/dto/UserResponseDto.java

feat/user ➡️ main
- 유저 정보 반환 API 추가 
`/api/user`
#7

✨feat: 유저 정보 반환 API 구현

---

src/main/java/CaffeineCoder/recipic/domain/comment/api/CommentController.java
src/main/java/CaffeineCoder/recipic/domain/comment/api/CommentService.java
src/main/java/CaffeineCoder/recipic/domain/comment/dao/CommentRepository.java
src/main/java/CaffeineCoder/recipic/domain/comment/dto/CommentDto.java
src/main/java/CaffeineCoder/recipic/domain/comment/dto/CommentResponseDto.java
src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeService.java
src/main/java/CaffeineCoder/recipic/domain/user/api/UserCommentApi.java

내가 작성한 댓글의 생성시간 추가 반환 구현
feat/ ➡️ main
- 내가 작성한 댓글 리스트에서 내가 작성한 댓글의 생성 시간을 추가
- 레시피 상세 페이지에서 댓글 목록 반환 시 내가 작성한 댓글인지 확인할 수 있는 dto 추가
- 내가 작성한 댓글 리스트 페이지네이션, 키워드 검색 삭제
x

feat: 댓글 기능 수정

---

src/main/java/CaffeineCoder/recipic/domain/jwtSecurity/config/SecurityConfig.java
src/main/java/CaffeineCoder/recipic/domain/jwtSecurity/jwt/TokenProvider.java
src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeRankService.java
src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeService.java
src/main/java/CaffeineCoder/recipic/domain/user/api/UserApi.java
src/main/java/CaffeineCoder/recipic/domain/user/dto/UserResponseDto.java

feat/API ➡️ main
- 권한이 없어도 확인 가능한 API 분리
close #85

Feat/api: 권한이 없어도 확인 가능한 API 분리

---

.gitignore
src/main/java/CaffeineCoder/recipic/domain/recipe/application/ImageService.java
src/main/java/CaffeineCoder/recipic/global/config/GoogleCloudStorageConfig.java

feat/image ➡️ main
- GCP CS image 업로드 구현 누락 코드 추가
x

✨feat: GCP CS image 업로드 구현 누락 코드 추가

---

src/main/java/CaffeineCoder/recipic/domain/comment/api/CommentController.java

feat/ ➡️ main
- 댓글 삭제 관련 api 수정
/api/recipe/comment?commentId={} : 댓글 삭제

feat: 댓글 삭제 api 변경

---

src/main/java/CaffeineCoder/recipic/domain/recipe/api/RecipeController.java
src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeService.java
src/main/java/CaffeineCoder/recipic/domain/recipe/domain/RecipeIngredient.java
src/main/java/CaffeineCoder/recipic/domain/recipe/domain/RecipeIngredientId.java
src/main/java/CaffeineCoder/recipic/domain/recipe/dto/RecipeRequestDto.java

feat/ ➡️ main
-  레시피 등록, 업데이트 부분 수정
x

feat: 레시피 등록, 업데이트 수정

---

src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeService.java
src/main/java/CaffeineCoder/recipic/domain/user/api/UserApi.java
src/main/java/CaffeineCoder/recipic/domain/user/application/UserScrapService.java
src/main/java/CaffeineCoder/recipic/domain/user/application/UserService.java
src/main/java/CaffeineCoder/recipic/domain/user/domain/User.java
src/main/java/CaffeineCoder/recipic/domain/user/dto/UserRequestDto.java
src/main/java/CaffeineCoder/recipic/domain/user/dto/UserResponseDto.java
src/main/java/CaffeineCoder/recipic/global/image/ImageService.java

- 유저 프로필 업데이트 API 추가 
`api/user/update`
close #99

feat: 유저 프로필 업데이트 API 추가 

---

src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeService.java
src/main/java/CaffeineCoder/recipic/domain/recipe/dto/RecipeDetailResponseDto.java
src/main/java/CaffeineCoder/recipic/domain/recipe/dto/RecipeResponseDto.java

feat/ ➡️ main
- 썸네일 이미지 저장 시 url 포함
- dto 속성 순서 변경
x

fix: change url of saveed recipe's thumbnailurl

---

src/main/java/CaffeineCoder/recipic/domain/announcement/api/AnnouncementAPI.java
src/main/java/CaffeineCoder/recipic/domain/announcement/application/AnnouncementService.java
src/main/java/CaffeineCoder/recipic/domain/announcement/dao/AnnouncementRepository.java
src/main/java/CaffeineCoder/recipic/domain/announcement/domain/Announcement.java
src/main/java/CaffeineCoder/recipic/domain/announcement/dto/AnnouncementRequestDto.java
src/main/java/CaffeineCoder/recipic/domain/announcement/dto/AnnouncementResponseDto.java
src/main/java/CaffeineCoder/recipic/domain/jwtSecurity/config/SecurityConfig.java
src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeService.java

feat/announcement ➡️ main
- 공지사항 API 추가
`api/announcement/list` : 공지사항 목록
`api/announcement/detail` : 상세 공지사항
#7

feat: 공지사항 API  추가

---

build.gradle
src/main/java/CaffeineCoder/recipic/domain/authentication/application/RedisService.java
src/main/java/CaffeineCoder/recipic/domain/jwtSecurity/controller/JwtController.java
src/main/java/CaffeineCoder/recipic/domain/jwtSecurity/service/JwtService.java
src/main/java/CaffeineCoder/recipic/global/config/RedisRepositoryConfig.java

feat: access token 관리용 redis 세팅

---

src/main/java/CaffeineCoder/recipic/domain/comment/api/CommentService.java
src/main/java/CaffeineCoder/recipic/domain/notification/api/NotificationApi.java
src/main/java/CaffeineCoder/recipic/domain/notification/application/NotificationService.java
src/main/java/CaffeineCoder/recipic/domain/notification/dao/NotificationRepository.java
src/main/java/CaffeineCoder/recipic/domain/notification/domain/Notification.java
src/main/java/CaffeineCoder/recipic/domain/notification/domain/ResourceNotFoundException.java
src/main/java/CaffeineCoder/recipic/domain/notification/dto/NotificationResponseDto.java
src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeService.java
src/main/java/CaffeineCoder/recipic/domain/scrap/api/ScrapService.java

feat/ ➡️ main
- 알림 기능 추가 : 내 게시글에 댓글이 작성됐을 때, 스크랩 되었을 때, 나의 댓글에 좋아요가 달렸을 때 알림 전송 
- /api/user/notifications : 알림 목록 반환
- /api/user/notifications/{notificationId} : 알림 확인

feat : 알람 기능 구현

---

src/main/java/CaffeineCoder/recipic/domain/comment/api/CommentService.java
src/main/java/CaffeineCoder/recipic/domain/comment/dao/CommentLikeRepository.java
src/main/java/CaffeineCoder/recipic/domain/comment/dao/CommentRepository.java
src/main/java/CaffeineCoder/recipic/domain/notification/application/NotificationService.java
src/main/java/CaffeineCoder/recipic/domain/notification/dao/NotificationRepository.java
src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeService.java
src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeUserHelper.java
src/main/java/CaffeineCoder/recipic/domain/recipe/dao/RecipeRepository.java
src/main/java/CaffeineCoder/recipic/domain/scrap/api/ScrapService.java
src/main/java/CaffeineCoder/recipic/domain/scrap/dao/ScrapRepository.java
src/main/java/CaffeineCoder/recipic/domain/user/api/UserApi.java
src/main/java/CaffeineCoder/recipic/domain/user/application/UserService.java

feat/ ➡️ main
- 회원 탈퇴시 유저의 데이터 삭제
x
스크랩 부분 삭제 확인
댓글 부분 삭제 확인
레시피 삭제 확인

feat: 회원 탈퇴시 데이터 삭제

---

src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeUserHelper.java

feat/ ➡️ main
- 레시피 상세 페이지 반환될 때 발생하는 에러 수정
x

레시피 상세 페이지 에러 수정

---

src/main/java/CaffeineCoder/recipic/domain/recipe/api/RecipeController.java
src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeService.java
src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeUserHelper.java
src/main/java/CaffeineCoder/recipic/domain/recipe/dao/RecipeRepository.java

feat/ ➡️ main
- 레시피 전체 리스트 반환 api 에서 발생하는 401 에러 해결
x

feat: 레시피 리스트 반환 에러 수정

---

src/main/java/CaffeineCoder/recipic/domain/recipe/application/RecipeService.java
src/main/java/CaffeineCoder/recipic/domain/user/application/UserService.java

feat/ ➡️ main
-  유저 탈퇴시 레시피 삭제 관련 문제 수정
x
유저 삭제시 
레시피 삭제 확인(39번이 삭제됨)

유저 삭제시 레시피 삭제 문제 수정

---

src/main/java/CaffeineCoder/recipic/domain/brand/api/BrandService.java

feat/ ➡️ main
- 베이스 재료 반환할 때 재료 이름과 사이즈가 같이 반환되도록 수정
x

베이스재료 사이즈 반환
